apiVersion: v1
kind: Service
metadata:
  name: inferno
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: inferno-app
      port: 4567
      targetPort: 4567
      protocol: TCP
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: inferno-app
